/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWarrantsRouteImport } from './routes/_authenticated/warrants'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTrasladoRouteImport } from './routes/_authenticated/traslado'
import { Route as AuthenticatedSalidaRouteImport } from './routes/_authenticated/salida'
import { Route as AuthenticatedMermasRouteImport } from './routes/_authenticated/mermas'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedLanceProduccionRouteImport } from './routes/_authenticated/lance-produccion'
import { Route as AuthenticatedKardexRouteImport } from './routes/_authenticated/kardex'
import { Route as AuthenticatedInventarioFisicoRouteImport } from './routes/_authenticated/inventario-fisico'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedEtiquetadoRouteImport } from './routes/_authenticated/etiquetado'
import { Route as AuthenticatedEntradaRouteImport } from './routes/_authenticated/entrada'
import { Route as AuthenticatedDescargasRouteImport } from './routes/_authenticated/descargas'
import { Route as AuthenticatedControlValesRouteImport } from './routes/_authenticated/control-vales'
import { Route as AuthenticatedControlTotalRouteImport } from './routes/_authenticated/control-total'
import { Route as AuthenticatedCertificacionRouteImport } from './routes/_authenticated/certificacion'
import { Route as AuthenticatedCatalogosRouteImport } from './routes/_authenticated/catalogos'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVentasIndexRouteImport } from './routes/_authenticated/ventas/index'
import { Route as AuthenticatedReportesIndexRouteImport } from './routes/_authenticated/reportes/index'
import { Route as AuthenticatedInsumosIndexRouteImport } from './routes/_authenticated/insumos.index'
import { Route as AuthenticatedVentasOrdenesRouteImport } from './routes/_authenticated/ventas/ordenes'
import { Route as AuthenticatedVentasGuiasRouteImport } from './routes/_authenticated/ventas/guias'
import { Route as AuthenticatedVentasFacturasRouteImport } from './routes/_authenticated/ventas/facturas'
import { Route as AuthenticatedVentasCotizacionesRouteImport } from './routes/_authenticated/ventas/cotizaciones'
import { Route as AuthenticatedReportesVencimientosRouteImport } from './routes/_authenticated/reportes/vencimientos'
import { Route as AuthenticatedReportesValorizadoRouteImport } from './routes/_authenticated/reportes/valorizado'
import { Route as AuthenticatedReportesJpgLoteRouteImport } from './routes/_authenticated/reportes/jpg-lote'
import { Route as AuthenticatedReportesGerenciaRouteImport } from './routes/_authenticated/reportes/gerencia'
import { Route as AuthenticatedReportesDespachosRouteImport } from './routes/_authenticated/reportes/despachos'
import { Route as AuthenticatedReportesAnaliticaRouteImport } from './routes/_authenticated/reportes/analitica'
import { Route as AuthenticatedInsumosReportesRouteImport } from './routes/_authenticated/insumos.reportes'
import { Route as AuthenticatedInsumosMovimientosRouteImport } from './routes/_authenticated/insumos.movimientos'
import { Route as AuthenticatedInsumosMapaRouteImport } from './routes/_authenticated/insumos.mapa'
import { Route as AuthenticatedInsumosControlRouteImport } from './routes/_authenticated/insumos.control'
import { Route as AuthenticatedInsumosCatalogoRouteImport } from './routes/_authenticated/insumos.catalogo'
import { Route as AuthenticatedEtiquetaLoteIdRouteImport } from './routes/_authenticated/etiqueta.$loteId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWarrantsRoute = AuthenticatedWarrantsRouteImport.update({
  id: '/warrants',
  path: '/warrants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrasladoRoute = AuthenticatedTrasladoRouteImport.update({
  id: '/traslado',
  path: '/traslado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalidaRoute = AuthenticatedSalidaRouteImport.update({
  id: '/salida',
  path: '/salida',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMermasRoute = AuthenticatedMermasRouteImport.update({
  id: '/mermas',
  path: '/mermas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLanceProduccionRoute =
  AuthenticatedLanceProduccionRouteImport.update({
    id: '/lance-produccion',
    path: '/lance-produccion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKardexRoute = AuthenticatedKardexRouteImport.update({
  id: '/kardex',
  path: '/kardex',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioFisicoRoute =
  AuthenticatedInventarioFisicoRouteImport.update({
    id: '/inventario-fisico',
    path: '/inventario-fisico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEtiquetadoRoute = AuthenticatedEtiquetadoRouteImport.update({
  id: '/etiquetado',
  path: '/etiquetado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntradaRoute = AuthenticatedEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDescargasRoute = AuthenticatedDescargasRouteImport.update({
  id: '/descargas',
  path: '/descargas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedControlValesRoute =
  AuthenticatedControlValesRouteImport.update({
    id: '/control-vales',
    path: '/control-vales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlTotalRoute =
  AuthenticatedControlTotalRouteImport.update({
    id: '/control-total',
    path: '/control-total',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificacionRoute =
  AuthenticatedCertificacionRouteImport.update({
    id: '/certificacion',
    path: '/certificacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogosRoute = AuthenticatedCatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVentasIndexRoute =
  AuthenticatedVentasIndexRouteImport.update({
    id: '/ventas/',
    path: '/ventas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesIndexRoute =
  AuthenticatedReportesIndexRouteImport.update({
    id: '/reportes/',
    path: '/reportes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsumosIndexRoute =
  AuthenticatedInsumosIndexRouteImport.update({
    id: '/insumos/',
    path: '/insumos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVentasOrdenesRoute =
  AuthenticatedVentasOrdenesRouteImport.update({
    id: '/ventas/ordenes',
    path: '/ventas/ordenes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVentasGuiasRoute =
  AuthenticatedVentasGuiasRouteImport.update({
    id: '/ventas/guias',
    path: '/ventas/guias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVentasFacturasRoute =
  AuthenticatedVentasFacturasRouteImport.update({
    id: '/ventas/facturas',
    path: '/ventas/facturas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVentasCotizacionesRoute =
  AuthenticatedVentasCotizacionesRouteImport.update({
    id: '/ventas/cotizaciones',
    path: '/ventas/cotizaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesVencimientosRoute =
  AuthenticatedReportesVencimientosRouteImport.update({
    id: '/reportes/vencimientos',
    path: '/reportes/vencimientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesValorizadoRoute =
  AuthenticatedReportesValorizadoRouteImport.update({
    id: '/reportes/valorizado',
    path: '/reportes/valorizado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesJpgLoteRoute =
  AuthenticatedReportesJpgLoteRouteImport.update({
    id: '/reportes/jpg-lote',
    path: '/reportes/jpg-lote',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesGerenciaRoute =
  AuthenticatedReportesGerenciaRouteImport.update({
    id: '/reportes/gerencia',
    path: '/reportes/gerencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesDespachosRoute =
  AuthenticatedReportesDespachosRouteImport.update({
    id: '/reportes/despachos',
    path: '/reportes/despachos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesAnaliticaRoute =
  AuthenticatedReportesAnaliticaRouteImport.update({
    id: '/reportes/analitica',
    path: '/reportes/analitica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsumosReportesRoute =
  AuthenticatedInsumosReportesRouteImport.update({
    id: '/insumos/reportes',
    path: '/insumos/reportes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsumosMovimientosRoute =
  AuthenticatedInsumosMovimientosRouteImport.update({
    id: '/insumos/movimientos',
    path: '/insumos/movimientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsumosMapaRoute =
  AuthenticatedInsumosMapaRouteImport.update({
    id: '/insumos/mapa',
    path: '/insumos/mapa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsumosControlRoute =
  AuthenticatedInsumosControlRouteImport.update({
    id: '/insumos/control',
    path: '/insumos/control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsumosCatalogoRoute =
  AuthenticatedInsumosCatalogoRouteImport.update({
    id: '/insumos/catalogo',
    path: '/insumos/catalogo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEtiquetaLoteIdRoute =
  AuthenticatedEtiquetaLoteIdRouteImport.update({
    id: '/etiqueta/$loteId',
    path: '/etiqueta/$loteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/catalogos': typeof AuthenticatedCatalogosRoute
  '/certificacion': typeof AuthenticatedCertificacionRoute
  '/control-total': typeof AuthenticatedControlTotalRoute
  '/control-vales': typeof AuthenticatedControlValesRoute
  '/descargas': typeof AuthenticatedDescargasRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/etiquetado': typeof AuthenticatedEtiquetadoRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/inventario-fisico': typeof AuthenticatedInventarioFisicoRoute
  '/kardex': typeof AuthenticatedKardexRoute
  '/lance-produccion': typeof AuthenticatedLanceProduccionRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/mermas': typeof AuthenticatedMermasRoute
  '/salida': typeof AuthenticatedSalidaRoute
  '/traslado': typeof AuthenticatedTrasladoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/warrants': typeof AuthenticatedWarrantsRoute
  '/etiqueta/$loteId': typeof AuthenticatedEtiquetaLoteIdRoute
  '/insumos/catalogo': typeof AuthenticatedInsumosCatalogoRoute
  '/insumos/control': typeof AuthenticatedInsumosControlRoute
  '/insumos/mapa': typeof AuthenticatedInsumosMapaRoute
  '/insumos/movimientos': typeof AuthenticatedInsumosMovimientosRoute
  '/insumos/reportes': typeof AuthenticatedInsumosReportesRoute
  '/reportes/analitica': typeof AuthenticatedReportesAnaliticaRoute
  '/reportes/despachos': typeof AuthenticatedReportesDespachosRoute
  '/reportes/gerencia': typeof AuthenticatedReportesGerenciaRoute
  '/reportes/jpg-lote': typeof AuthenticatedReportesJpgLoteRoute
  '/reportes/valorizado': typeof AuthenticatedReportesValorizadoRoute
  '/reportes/vencimientos': typeof AuthenticatedReportesVencimientosRoute
  '/ventas/cotizaciones': typeof AuthenticatedVentasCotizacionesRoute
  '/ventas/facturas': typeof AuthenticatedVentasFacturasRoute
  '/ventas/guias': typeof AuthenticatedVentasGuiasRoute
  '/ventas/ordenes': typeof AuthenticatedVentasOrdenesRoute
  '/insumos/': typeof AuthenticatedInsumosIndexRoute
  '/reportes/': typeof AuthenticatedReportesIndexRoute
  '/ventas/': typeof AuthenticatedVentasIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/catalogos': typeof AuthenticatedCatalogosRoute
  '/certificacion': typeof AuthenticatedCertificacionRoute
  '/control-total': typeof AuthenticatedControlTotalRoute
  '/control-vales': typeof AuthenticatedControlValesRoute
  '/descargas': typeof AuthenticatedDescargasRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/etiquetado': typeof AuthenticatedEtiquetadoRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/inventario-fisico': typeof AuthenticatedInventarioFisicoRoute
  '/kardex': typeof AuthenticatedKardexRoute
  '/lance-produccion': typeof AuthenticatedLanceProduccionRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/mermas': typeof AuthenticatedMermasRoute
  '/salida': typeof AuthenticatedSalidaRoute
  '/traslado': typeof AuthenticatedTrasladoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/warrants': typeof AuthenticatedWarrantsRoute
  '/': typeof AuthenticatedIndexRoute
  '/etiqueta/$loteId': typeof AuthenticatedEtiquetaLoteIdRoute
  '/insumos/catalogo': typeof AuthenticatedInsumosCatalogoRoute
  '/insumos/control': typeof AuthenticatedInsumosControlRoute
  '/insumos/mapa': typeof AuthenticatedInsumosMapaRoute
  '/insumos/movimientos': typeof AuthenticatedInsumosMovimientosRoute
  '/insumos/reportes': typeof AuthenticatedInsumosReportesRoute
  '/reportes/analitica': typeof AuthenticatedReportesAnaliticaRoute
  '/reportes/despachos': typeof AuthenticatedReportesDespachosRoute
  '/reportes/gerencia': typeof AuthenticatedReportesGerenciaRoute
  '/reportes/jpg-lote': typeof AuthenticatedReportesJpgLoteRoute
  '/reportes/valorizado': typeof AuthenticatedReportesValorizadoRoute
  '/reportes/vencimientos': typeof AuthenticatedReportesVencimientosRoute
  '/ventas/cotizaciones': typeof AuthenticatedVentasCotizacionesRoute
  '/ventas/facturas': typeof AuthenticatedVentasFacturasRoute
  '/ventas/guias': typeof AuthenticatedVentasGuiasRoute
  '/ventas/ordenes': typeof AuthenticatedVentasOrdenesRoute
  '/insumos': typeof AuthenticatedInsumosIndexRoute
  '/reportes': typeof AuthenticatedReportesIndexRoute
  '/ventas': typeof AuthenticatedVentasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/catalogos': typeof AuthenticatedCatalogosRoute
  '/_authenticated/certificacion': typeof AuthenticatedCertificacionRoute
  '/_authenticated/control-total': typeof AuthenticatedControlTotalRoute
  '/_authenticated/control-vales': typeof AuthenticatedControlValesRoute
  '/_authenticated/descargas': typeof AuthenticatedDescargasRoute
  '/_authenticated/entrada': typeof AuthenticatedEntradaRoute
  '/_authenticated/etiquetado': typeof AuthenticatedEtiquetadoRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/inventario-fisico': typeof AuthenticatedInventarioFisicoRoute
  '/_authenticated/kardex': typeof AuthenticatedKardexRoute
  '/_authenticated/lance-produccion': typeof AuthenticatedLanceProduccionRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/mermas': typeof AuthenticatedMermasRoute
  '/_authenticated/salida': typeof AuthenticatedSalidaRoute
  '/_authenticated/traslado': typeof AuthenticatedTrasladoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/warrants': typeof AuthenticatedWarrantsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/etiqueta/$loteId': typeof AuthenticatedEtiquetaLoteIdRoute
  '/_authenticated/insumos/catalogo': typeof AuthenticatedInsumosCatalogoRoute
  '/_authenticated/insumos/control': typeof AuthenticatedInsumosControlRoute
  '/_authenticated/insumos/mapa': typeof AuthenticatedInsumosMapaRoute
  '/_authenticated/insumos/movimientos': typeof AuthenticatedInsumosMovimientosRoute
  '/_authenticated/insumos/reportes': typeof AuthenticatedInsumosReportesRoute
  '/_authenticated/reportes/analitica': typeof AuthenticatedReportesAnaliticaRoute
  '/_authenticated/reportes/despachos': typeof AuthenticatedReportesDespachosRoute
  '/_authenticated/reportes/gerencia': typeof AuthenticatedReportesGerenciaRoute
  '/_authenticated/reportes/jpg-lote': typeof AuthenticatedReportesJpgLoteRoute
  '/_authenticated/reportes/valorizado': typeof AuthenticatedReportesValorizadoRoute
  '/_authenticated/reportes/vencimientos': typeof AuthenticatedReportesVencimientosRoute
  '/_authenticated/ventas/cotizaciones': typeof AuthenticatedVentasCotizacionesRoute
  '/_authenticated/ventas/facturas': typeof AuthenticatedVentasFacturasRoute
  '/_authenticated/ventas/guias': typeof AuthenticatedVentasGuiasRoute
  '/_authenticated/ventas/ordenes': typeof AuthenticatedVentasOrdenesRoute
  '/_authenticated/insumos/': typeof AuthenticatedInsumosIndexRoute
  '/_authenticated/reportes/': typeof AuthenticatedReportesIndexRoute
  '/_authenticated/ventas/': typeof AuthenticatedVentasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/auditoria'
    | '/catalogos'
    | '/certificacion'
    | '/control-total'
    | '/control-vales'
    | '/descargas'
    | '/entrada'
    | '/etiquetado'
    | '/historial'
    | '/importar'
    | '/inventario'
    | '/inventario-fisico'
    | '/kardex'
    | '/lance-produccion'
    | '/mapa'
    | '/mermas'
    | '/salida'
    | '/traslado'
    | '/usuarios'
    | '/warrants'
    | '/etiqueta/$loteId'
    | '/insumos/catalogo'
    | '/insumos/control'
    | '/insumos/mapa'
    | '/insumos/movimientos'
    | '/insumos/reportes'
    | '/reportes/analitica'
    | '/reportes/despachos'
    | '/reportes/gerencia'
    | '/reportes/jpg-lote'
    | '/reportes/valorizado'
    | '/reportes/vencimientos'
    | '/ventas/cotizaciones'
    | '/ventas/facturas'
    | '/ventas/guias'
    | '/ventas/ordenes'
    | '/insumos/'
    | '/reportes/'
    | '/ventas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/auditoria'
    | '/catalogos'
    | '/certificacion'
    | '/control-total'
    | '/control-vales'
    | '/descargas'
    | '/entrada'
    | '/etiquetado'
    | '/historial'
    | '/importar'
    | '/inventario'
    | '/inventario-fisico'
    | '/kardex'
    | '/lance-produccion'
    | '/mapa'
    | '/mermas'
    | '/salida'
    | '/traslado'
    | '/usuarios'
    | '/warrants'
    | '/'
    | '/etiqueta/$loteId'
    | '/insumos/catalogo'
    | '/insumos/control'
    | '/insumos/mapa'
    | '/insumos/movimientos'
    | '/insumos/reportes'
    | '/reportes/analitica'
    | '/reportes/despachos'
    | '/reportes/gerencia'
    | '/reportes/jpg-lote'
    | '/reportes/valorizado'
    | '/reportes/vencimientos'
    | '/ventas/cotizaciones'
    | '/ventas/facturas'
    | '/ventas/guias'
    | '/ventas/ordenes'
    | '/insumos'
    | '/reportes'
    | '/ventas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/auditoria'
    | '/_authenticated/catalogos'
    | '/_authenticated/certificacion'
    | '/_authenticated/control-total'
    | '/_authenticated/control-vales'
    | '/_authenticated/descargas'
    | '/_authenticated/entrada'
    | '/_authenticated/etiquetado'
    | '/_authenticated/historial'
    | '/_authenticated/importar'
    | '/_authenticated/inventario'
    | '/_authenticated/inventario-fisico'
    | '/_authenticated/kardex'
    | '/_authenticated/lance-produccion'
    | '/_authenticated/mapa'
    | '/_authenticated/mermas'
    | '/_authenticated/salida'
    | '/_authenticated/traslado'
    | '/_authenticated/usuarios'
    | '/_authenticated/warrants'
    | '/_authenticated/'
    | '/_authenticated/etiqueta/$loteId'
    | '/_authenticated/insumos/catalogo'
    | '/_authenticated/insumos/control'
    | '/_authenticated/insumos/mapa'
    | '/_authenticated/insumos/movimientos'
    | '/_authenticated/insumos/reportes'
    | '/_authenticated/reportes/analitica'
    | '/_authenticated/reportes/despachos'
    | '/_authenticated/reportes/gerencia'
    | '/_authenticated/reportes/jpg-lote'
    | '/_authenticated/reportes/valorizado'
    | '/_authenticated/reportes/vencimientos'
    | '/_authenticated/ventas/cotizaciones'
    | '/_authenticated/ventas/facturas'
    | '/_authenticated/ventas/guias'
    | '/_authenticated/ventas/ordenes'
    | '/_authenticated/insumos/'
    | '/_authenticated/reportes/'
    | '/_authenticated/ventas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warrants': {
      id: '/_authenticated/warrants'
      path: '/warrants'
      fullPath: '/warrants'
      preLoaderRoute: typeof AuthenticatedWarrantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/traslado': {
      id: '/_authenticated/traslado'
      path: '/traslado'
      fullPath: '/traslado'
      preLoaderRoute: typeof AuthenticatedTrasladoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salida': {
      id: '/_authenticated/salida'
      path: '/salida'
      fullPath: '/salida'
      preLoaderRoute: typeof AuthenticatedSalidaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mermas': {
      id: '/_authenticated/mermas'
      path: '/mermas'
      fullPath: '/mermas'
      preLoaderRoute: typeof AuthenticatedMermasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lance-produccion': {
      id: '/_authenticated/lance-produccion'
      path: '/lance-produccion'
      fullPath: '/lance-produccion'
      preLoaderRoute: typeof AuthenticatedLanceProduccionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kardex': {
      id: '/_authenticated/kardex'
      path: '/kardex'
      fullPath: '/kardex'
      preLoaderRoute: typeof AuthenticatedKardexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario-fisico': {
      id: '/_authenticated/inventario-fisico'
      path: '/inventario-fisico'
      fullPath: '/inventario-fisico'
      preLoaderRoute: typeof AuthenticatedInventarioFisicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etiquetado': {
      id: '/_authenticated/etiquetado'
      path: '/etiquetado'
      fullPath: '/etiquetado'
      preLoaderRoute: typeof AuthenticatedEtiquetadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrada': {
      id: '/_authenticated/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof AuthenticatedEntradaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/descargas': {
      id: '/_authenticated/descargas'
      path: '/descargas'
      fullPath: '/descargas'
      preLoaderRoute: typeof AuthenticatedDescargasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control-vales': {
      id: '/_authenticated/control-vales'
      path: '/control-vales'
      fullPath: '/control-vales'
      preLoaderRoute: typeof AuthenticatedControlValesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control-total': {
      id: '/_authenticated/control-total'
      path: '/control-total'
      fullPath: '/control-total'
      preLoaderRoute: typeof AuthenticatedControlTotalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificacion': {
      id: '/_authenticated/certificacion'
      path: '/certificacion'
      fullPath: '/certificacion'
      preLoaderRoute: typeof AuthenticatedCertificacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogos': {
      id: '/_authenticated/catalogos'
      path: '/catalogos'
      fullPath: '/catalogos'
      preLoaderRoute: typeof AuthenticatedCatalogosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas/': {
      id: '/_authenticated/ventas/'
      path: '/ventas'
      fullPath: '/ventas/'
      preLoaderRoute: typeof AuthenticatedVentasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes/': {
      id: '/_authenticated/reportes/'
      path: '/reportes'
      fullPath: '/reportes/'
      preLoaderRoute: typeof AuthenticatedReportesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insumos/': {
      id: '/_authenticated/insumos/'
      path: '/insumos'
      fullPath: '/insumos/'
      preLoaderRoute: typeof AuthenticatedInsumosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas/ordenes': {
      id: '/_authenticated/ventas/ordenes'
      path: '/ventas/ordenes'
      fullPath: '/ventas/ordenes'
      preLoaderRoute: typeof AuthenticatedVentasOrdenesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas/guias': {
      id: '/_authenticated/ventas/guias'
      path: '/ventas/guias'
      fullPath: '/ventas/guias'
      preLoaderRoute: typeof AuthenticatedVentasGuiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas/facturas': {
      id: '/_authenticated/ventas/facturas'
      path: '/ventas/facturas'
      fullPath: '/ventas/facturas'
      preLoaderRoute: typeof AuthenticatedVentasFacturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas/cotizaciones': {
      id: '/_authenticated/ventas/cotizaciones'
      path: '/ventas/cotizaciones'
      fullPath: '/ventas/cotizaciones'
      preLoaderRoute: typeof AuthenticatedVentasCotizacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes/vencimientos': {
      id: '/_authenticated/reportes/vencimientos'
      path: '/reportes/vencimientos'
      fullPath: '/reportes/vencimientos'
      preLoaderRoute: typeof AuthenticatedReportesVencimientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes/valorizado': {
      id: '/_authenticated/reportes/valorizado'
      path: '/reportes/valorizado'
      fullPath: '/reportes/valorizado'
      preLoaderRoute: typeof AuthenticatedReportesValorizadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes/jpg-lote': {
      id: '/_authenticated/reportes/jpg-lote'
      path: '/reportes/jpg-lote'
      fullPath: '/reportes/jpg-lote'
      preLoaderRoute: typeof AuthenticatedReportesJpgLoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes/gerencia': {
      id: '/_authenticated/reportes/gerencia'
      path: '/reportes/gerencia'
      fullPath: '/reportes/gerencia'
      preLoaderRoute: typeof AuthenticatedReportesGerenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes/despachos': {
      id: '/_authenticated/reportes/despachos'
      path: '/reportes/despachos'
      fullPath: '/reportes/despachos'
      preLoaderRoute: typeof AuthenticatedReportesDespachosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes/analitica': {
      id: '/_authenticated/reportes/analitica'
      path: '/reportes/analitica'
      fullPath: '/reportes/analitica'
      preLoaderRoute: typeof AuthenticatedReportesAnaliticaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insumos/reportes': {
      id: '/_authenticated/insumos/reportes'
      path: '/insumos/reportes'
      fullPath: '/insumos/reportes'
      preLoaderRoute: typeof AuthenticatedInsumosReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insumos/movimientos': {
      id: '/_authenticated/insumos/movimientos'
      path: '/insumos/movimientos'
      fullPath: '/insumos/movimientos'
      preLoaderRoute: typeof AuthenticatedInsumosMovimientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insumos/mapa': {
      id: '/_authenticated/insumos/mapa'
      path: '/insumos/mapa'
      fullPath: '/insumos/mapa'
      preLoaderRoute: typeof AuthenticatedInsumosMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insumos/control': {
      id: '/_authenticated/insumos/control'
      path: '/insumos/control'
      fullPath: '/insumos/control'
      preLoaderRoute: typeof AuthenticatedInsumosControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insumos/catalogo': {
      id: '/_authenticated/insumos/catalogo'
      path: '/insumos/catalogo'
      fullPath: '/insumos/catalogo'
      preLoaderRoute: typeof AuthenticatedInsumosCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etiqueta/$loteId': {
      id: '/_authenticated/etiqueta/$loteId'
      path: '/etiqueta/$loteId'
      fullPath: '/etiqueta/$loteId'
      preLoaderRoute: typeof AuthenticatedEtiquetaLoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCatalogosRoute: typeof AuthenticatedCatalogosRoute
  AuthenticatedCertificacionRoute: typeof AuthenticatedCertificacionRoute
  AuthenticatedControlTotalRoute: typeof AuthenticatedControlTotalRoute
  AuthenticatedControlValesRoute: typeof AuthenticatedControlValesRoute
  AuthenticatedDescargasRoute: typeof AuthenticatedDescargasRoute
  AuthenticatedEntradaRoute: typeof AuthenticatedEntradaRoute
  AuthenticatedEtiquetadoRoute: typeof AuthenticatedEtiquetadoRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedInventarioFisicoRoute: typeof AuthenticatedInventarioFisicoRoute
  AuthenticatedKardexRoute: typeof AuthenticatedKardexRoute
  AuthenticatedLanceProduccionRoute: typeof AuthenticatedLanceProduccionRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedMermasRoute: typeof AuthenticatedMermasRoute
  AuthenticatedSalidaRoute: typeof AuthenticatedSalidaRoute
  AuthenticatedTrasladoRoute: typeof AuthenticatedTrasladoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedWarrantsRoute: typeof AuthenticatedWarrantsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEtiquetaLoteIdRoute: typeof AuthenticatedEtiquetaLoteIdRoute
  AuthenticatedInsumosCatalogoRoute: typeof AuthenticatedInsumosCatalogoRoute
  AuthenticatedInsumosControlRoute: typeof AuthenticatedInsumosControlRoute
  AuthenticatedInsumosMapaRoute: typeof AuthenticatedInsumosMapaRoute
  AuthenticatedInsumosMovimientosRoute: typeof AuthenticatedInsumosMovimientosRoute
  AuthenticatedInsumosReportesRoute: typeof AuthenticatedInsumosReportesRoute
  AuthenticatedReportesAnaliticaRoute: typeof AuthenticatedReportesAnaliticaRoute
  AuthenticatedReportesDespachosRoute: typeof AuthenticatedReportesDespachosRoute
  AuthenticatedReportesGerenciaRoute: typeof AuthenticatedReportesGerenciaRoute
  AuthenticatedReportesJpgLoteRoute: typeof AuthenticatedReportesJpgLoteRoute
  AuthenticatedReportesValorizadoRoute: typeof AuthenticatedReportesValorizadoRoute
  AuthenticatedReportesVencimientosRoute: typeof AuthenticatedReportesVencimientosRoute
  AuthenticatedVentasCotizacionesRoute: typeof AuthenticatedVentasCotizacionesRoute
  AuthenticatedVentasFacturasRoute: typeof AuthenticatedVentasFacturasRoute
  AuthenticatedVentasGuiasRoute: typeof AuthenticatedVentasGuiasRoute
  AuthenticatedVentasOrdenesRoute: typeof AuthenticatedVentasOrdenesRoute
  AuthenticatedInsumosIndexRoute: typeof AuthenticatedInsumosIndexRoute
  AuthenticatedReportesIndexRoute: typeof AuthenticatedReportesIndexRoute
  AuthenticatedVentasIndexRoute: typeof AuthenticatedVentasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCatalogosRoute: AuthenticatedCatalogosRoute,
  AuthenticatedCertificacionRoute: AuthenticatedCertificacionRoute,
  AuthenticatedControlTotalRoute: AuthenticatedControlTotalRoute,
  AuthenticatedControlValesRoute: AuthenticatedControlValesRoute,
  AuthenticatedDescargasRoute: AuthenticatedDescargasRoute,
  AuthenticatedEntradaRoute: AuthenticatedEntradaRoute,
  AuthenticatedEtiquetadoRoute: AuthenticatedEtiquetadoRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedInventarioFisicoRoute: AuthenticatedInventarioFisicoRoute,
  AuthenticatedKardexRoute: AuthenticatedKardexRoute,
  AuthenticatedLanceProduccionRoute: AuthenticatedLanceProduccionRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedMermasRoute: AuthenticatedMermasRoute,
  AuthenticatedSalidaRoute: AuthenticatedSalidaRoute,
  AuthenticatedTrasladoRoute: AuthenticatedTrasladoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedWarrantsRoute: AuthenticatedWarrantsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEtiquetaLoteIdRoute: AuthenticatedEtiquetaLoteIdRoute,
  AuthenticatedInsumosCatalogoRoute: AuthenticatedInsumosCatalogoRoute,
  AuthenticatedInsumosControlRoute: AuthenticatedInsumosControlRoute,
  AuthenticatedInsumosMapaRoute: AuthenticatedInsumosMapaRoute,
  AuthenticatedInsumosMovimientosRoute: AuthenticatedInsumosMovimientosRoute,
  AuthenticatedInsumosReportesRoute: AuthenticatedInsumosReportesRoute,
  AuthenticatedReportesAnaliticaRoute: AuthenticatedReportesAnaliticaRoute,
  AuthenticatedReportesDespachosRoute: AuthenticatedReportesDespachosRoute,
  AuthenticatedReportesGerenciaRoute: AuthenticatedReportesGerenciaRoute,
  AuthenticatedReportesJpgLoteRoute: AuthenticatedReportesJpgLoteRoute,
  AuthenticatedReportesValorizadoRoute: AuthenticatedReportesValorizadoRoute,
  AuthenticatedReportesVencimientosRoute:
    AuthenticatedReportesVencimientosRoute,
  AuthenticatedVentasCotizacionesRoute: AuthenticatedVentasCotizacionesRoute,
  AuthenticatedVentasFacturasRoute: AuthenticatedVentasFacturasRoute,
  AuthenticatedVentasGuiasRoute: AuthenticatedVentasGuiasRoute,
  AuthenticatedVentasOrdenesRoute: AuthenticatedVentasOrdenesRoute,
  AuthenticatedInsumosIndexRoute: AuthenticatedInsumosIndexRoute,
  AuthenticatedReportesIndexRoute: AuthenticatedReportesIndexRoute,
  AuthenticatedVentasIndexRoute: AuthenticatedVentasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
