
ALTER TYPE public.presentacion_t ADD VALUE IF NOT EXISTS 'FILETE CON PIEL';
ALTER TYPE public.presentacion_t ADD VALUE IF NOT EXISTS 'FILETE CON SANGACHO';
ALTER TYPE public.presentacion_t ADD VALUE IF NOT EXISTS 'FILETE SIN SANGACHO';
ALTER TYPE public.presentacion_t ADD VALUE IF NOT EXISTS 'CUBOS';
ALTER TYPE public.presentacion_t ADD VALUE IF NOT EXISTS 'MEDALLON';
ALTER TYPE public.presentacion_t ADD VALUE IF NOT EXISTS 'TROZOS';
ALTER TYPE public.presentacion_t ADD VALUE IF NOT EXISTS 'SOLIDO';
ALTER TYPE public.presentacion_t ADD VALUE IF NOT EXISTS 'LOMITOS';

ALTER TYPE public.especie_t ADD VALUE IF NOT EXISTS 'CALAMAR';
ALTER TYPE public.especie_t ADD VALUE IF NOT EXISTS 'SARDINA';
ALTER TYPE public.especie_t ADD VALUE IF NOT EXISTS 'MELVA';
ALTER TYPE public.especie_t ADD VALUE IF NOT EXISTS 'POTA';
ALTER TYPE public.especie_t ADD VALUE IF NOT EXISTS 'TRUCHA';
ALTER TYPE public.especie_t ADD VALUE IF NOT EXISTS 'PULPO';

ALTER TYPE public.liquido_t ADD VALUE IF NOT EXISTS 'SALSA DE TOMATE';
ALTER TYPE public.liquido_t ADD VALUE IF NOT EXISTS 'SALSA DE TOMATE PICANTE';
ALTER TYPE public.liquido_t ADD VALUE IF NOT EXISTS 'SALSA DE ESCABECHE';
